In [3]:
from unittest.mock import inplace

import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns

In [4]:
df = pd.read_csv('HousingData.csv')
display(df)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0


In [5]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2


In [6]:
df.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [8]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,486.000000,486.000000,486.000000,486.000000,506.000000,506.000000,486.000000,506.000000,506.000000,506.000000,506.000000,506.000000,486.000000,506.000000
mean,3.611874,11.211934,11.083992,0.069959,0.554695,6.284634,68.518519,3.795043,9.549407,408.237154,18.455534,356.674032,12.715432,22.532806
std,8.720192,23.388876,6.835896,0.255340,0.115878,0.702617,27.999513,2.105710,8.707259,168.537116,2.164946,91.294864,7.155871,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081900,0.000000,5.190000,0.000000,0.449000,5.885500,45.175000,2.100175,4.000000,279.000000,17.400000,375.377500,7.125000,17.025000
50%,0.253715,0.000000,9.690000,0.000000,0.538000,6.208500,76.800000,3.207450,5.000000,330.000000,19.050000,391.440000,11.430000,21.200000
75%,3.560263,12.500000,18.100000,0.000000,0.624000,6.623500,93.975000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000


In [9]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [10]:
df.dtypes

,0
CRIM,float64
ZN,float64
INDUS,float64
CHAS,float64
NOX,float64
RM,float64
AGE,float64
DIS,float64
RAD,int64
TAX,int64


In [11]:
df.keys()

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [41]:
df.dropna(inplace=True)
df


,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9


In [42]:
#x = pd.DataFrame(np.c_[df['lstat'] , df['rm']],columns=['lstat','rm'])
x = df.drop('MEDV',axis=1)
y = df['MEDV']

In [43]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64


In [44]:
y

,MEDV
0,24.0
1,21.6
2,34.7
3,33.4
5,28.7
...,...
499,17.5
500,16.8
502,20.6
503,23.9


In [45]:
x.shape

(394, 13)

In [46]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(x,y,
                                                   random_state=0,
                                                   train_size=0.25)

In [47]:
xtrain

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24,666,20.2,396.21,18.68
114,0.14231,0.0,10.01,0.0,0.547,6.254,84.2,2.2565,6,432,17.8,388.74,10.45
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4,711,20.1,390.11,18.07
225,0.52693,0.0,6.20,0.0,0.504,8.725,83.0,2.8944,8,307,17.4,382.00,4.63
328,0.06617,0.0,3.24,0.0,0.460,5.868,25.8,5.2146,4,430,16.9,382.44,9.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,18.08460,0.0,18.10,0.0,0.679,6.434,100.0,1.8347,24,666,20.2,27.25,29.05
248,0.16439,22.0,5.86,0.0,0.431,6.433,49.1,7.8265,7,330,19.1,374.71,9.52
141,1.62864,0.0,21.89,0.0,0.624,5.019,100.0,1.4394,4,437,21.2,396.90,34.41
57,0.01432,100.0,1.32,0.0,0.411,6.816,40.5,8.3248,5,256,15.1,392.90,3.95


In [48]:
xtrain.shape

(98, 13)

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
regressor = LinearRegression()

In [51]:
regressor.fit(xtrain,ytrain)

LinearRegression()

In [52]:
regressor.coef_

array([ 1.75975218e-01,  7.77147682e-02,  2.60419256e-01,  6.33846719e+00,
       -2.93061382e+01,  5.82729546e+00, -5.37263281e-02, -1.90814475e+00,
        2.22346169e-01, -1.84787607e-02, -6.90415273e-01,  2.16025588e-02,
       -2.14000514e-01])

In [53]:
regressor.intercept_

np.float64(22.082718741685742)

In [55]:
y_pred = regressor.predict(xtest)

In [56]:
y_pred

array([18.13421236, 18.28733097, 26.87837986, 43.56379343, 15.92755481,
       18.86949427, 30.52886468, 18.8454982 , 28.63092191, 13.80088065,
       22.81920539, 14.56838531, 23.50123077, 26.44263288,  7.8511206 ,
       33.24047581, 27.30102889, 28.87927318, 25.06698774, 28.97400458,
       18.89930863, 31.00124269, 20.95113574, 19.22140024, 19.99894217,
       23.44632338, 20.87698289, 25.94521905, 23.96560489, 25.15405914,
        4.72826494, 27.01642978, 18.07773051, 26.34296027, 15.8532341 ,
       15.53025731, 22.35979007, 17.58849618, 22.53400917, 12.4374363 ,
       24.18575233, 14.37704968, 32.79538269, 22.88844748, 34.1081181 ,
       13.26891517, 21.72014732, 17.32507934,  9.98582497, 16.46063827,
       19.83451052, 18.43444927, 12.45520486, 34.1586355 , 20.76429967,
       21.44965762, 18.6407481 , 17.60168441, 21.13549763, 28.60903074,
       17.7075007 , 19.85533163, 21.01455154, 18.5676957 , 21.72916782,
       44.14285629, 18.74430969, 30.07950388, 15.38604656, 32.36

In [57]:
y_pred.shape

(296,)

In [58]:
result = pd.DataFrame({'Actual' : ytest , 'Predicted' : y_pred})
result

,Actual,Predicted
136,17.4,18.134212
360,25.0,18.287331
81,23.9,26.878380
195,50.0,43.563793
421,14.2,15.927555
...,...,...
242,22.2,23.937002
27,14.8,14.211394
52,25.0,28.376194
0,24.0,27.022374


In [60]:
residual_err = abs(ytest - y_pred)
residual_err

,MEDV
136,0.734212
360,6.712669
81,2.978380
195,6.436207
421,1.727555
...,...
242,1.737002
27,0.588606
52,3.376194
0,3.022374


In [61]:
sum(residual_err)/len(residual_err)

3.858015766723094

In [66]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest,y_pred)

3.8580157667230948

In [64]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(ytest,y_pred)

0.22758755777607692

In [67]:
regressor.score(xtest,ytest)

0.6316244536004998

In [68]:
from sklearn.metrics import r2_score
r2_score(ytest,y_pred)

0.6316244536004998

In [81]:
new = [[.658,0,8.7584,0,0.757,5.742387,69.5,3.587,4,307,22,49.99,11.4]]
new_data = {k : v for k,v in zip(xtrain.columns,*new)}
df_new = pd.DataFrame(new_data,index=pd.interval_range(start=0,end=len(new)))

In [82]:
regressor.predict(df_new)

array([3.84628572])